server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
#    false 关闭模板的缓存
    cache: false
  rabbitmq:
    host: 120.78.170.24
    username: bruce
    password: 103021
    virtual-host: /peanut

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

peanut:
  page:
    destPath: E:\nginx\nginx-1.17.2\html\item