server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
#    false 关闭模板的缓存
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

peanut:
  page:
    destPath: E:\nginx\nginx-1.17.2\html\item