server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 120.78.170.24:9300
  jackson:
#    返回前台时不显示为空的字段
    default-property-inclusion: non_null
  rabbitmq:
    host: 120.78.170.24
    username: bruce
    password: 103021
    virtual-host: /peanut
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1


#请求处理的超时时间
ribbon.ReadTimeout: 120000
#请求连接的超时时间
ribbon.ConnectTimeout: 30000